### ISSUE TITLE
Incomplete Pre-trained Weights

### ISSUE THREAD

**Issue by raviy0807** [CHELSEA234/Multi-domain-learning-FAS#10]
Hi @CHELSEA234 ,

Thanks for directing the link. I am trying to run the script for the inference : source/test_architecture.py

In this file, it requires trained model with 2 other folders of RE & G_Op as written here : https://github.com/CHELSEA234/Multi-domain-learning-FAS/blob/main/source/test_architecture.py#L68

Please guide me on this

Thanks

**Comment by CHELSEA234** [comment]
Thank you for noticing this. I have updated the test script and upload the pretrained weights now.
