### ISSUE TITLE
How to get live/spoof?

### ISSUE THREAD

**Issue by angelabr** [CHELSEA234/Multi-domain-learning-FAS#11]
hi, I see the model outputs depth, region, content, and additive traces, how is it possible to transform this to live/spoof to replicate your paper?

**Comment by CHELSEA234** [comment]
Thank you for the question. In my script, i have the live reconstruction, which is `recon` variable in `https://github.com/CHELSEA234/Multi-domain-learning-FAS/blob/main/source_SiWMv2/train_architecture.py#L230`. 
Also, I do not have spoof reconstruction as the original PAMI paper has.

**Comment by angelabr** [comment]
Thank you for your prompt reply, I don't understand what is the purpose of recon though, is it possible or can it be used to obtain kind of a numerical output that states whether an image is live or spoof?
