### ISSUE TITLE
How to use recon

### ISSUE THREAD

**Issue by angelabr** [CHELSEA234/Multi-domain-learning-FAS#12]
Hi, I don't understand what is the purpose of recon of the liveness image, is it possible or can it be used to obtain kind of a numerical output that states whether an image is live or spoof?

**Comment by CHELSEA234** [comment]
@angelabr 
I am sorry for the late response. We want to obtain the trace by subtracting a spoof image and its corresponding live image. However, we do not have the corresponding live image, so we use recon to micmic the corresponding live image. This imitation is the purpose to have recon.

**Comment by tangwudu** [comment]
Then how can we use the recon and d_total_loss for live and spoof classification?

**Comment by tangwudu** [comment]
I think I have found it. Can refer to source_SiW_Mv2/inference.py for final score and decision.

**Comment by tangwudu** [comment]
But may need some adjustment with the hyper parameters.
