### ISSUE TITLE
 Help with downloading the dataset SIW

### ISSUE THREAD

**Issue by nguyenthuy1681999** [CHELSEA234/Multi-domain-learning-FAS#13]
Hello,
I sent the request form and the signed DRA to ask for the download link of the SiW dataset a month ago but I haven't received any reply so far. I also sent you an email a few days ago asking for help. If possible, can you check my email and help me with downloading the dataset.
Thank you very much.

**Comment by CHELSEA234** [comment]
we release the siw dataset monthly and could you please let me know your email address?

**Comment by lehoangHUST** [comment]
hello @CHELSEA234  Can you share that dataset with me? Thank you very much
My email: lehuyhoang30122000@gmail.com

**Comment by nguyenthuy1681999** [comment]
My email is:
ThuyNTT.B22CHCS009@stu.ptit.edu.vn
Thanks

**Comment by nguyenthuy1681999** [comment]
> we release the siw dataset monthly and could you please let me know your email address?

Hello, I am a computer vision researcher. I know you through your articles and the models you are researching. I am very impressed with your research. I hope we can get acquainted and learn from each other. My email is [ThuyNTT.B22CHCS009@stu.ptit.edu.vn](mailto:ThuyNTT.B22CHCS009@stu.ptit.edu.vn). Do you use Twitter, Telegram, or WhatsApp? It would be great to connect with you to exchange knowledge.
Thank you very much.

**Comment by CHELSEA234** [comment]
@lehoangHUST please sign the DRA form first and then we can distribute the dataset.

**Comment by CHELSEA234** [comment]
@nguyenthuy1681999 I have replied your email and please kindly review.

**Comment by nguyenthuy1681999** [comment]
@CHELSEA234 
Hi, 
Sorry, I couldn't find your email in my Inbox. Can you send it again to my email "
ThuyNTT.B22CHCS009@stu.ptit.edu.vn" and CC to my gmail "nguyenthuthuy1681999@gmail.com" to make sure I won't miss it?  
Thanks so much.

**Comment by CHELSEA234** [comment]
i think I have shared with you the dataset. Thank for your interests, and please feel free reopening this issue.

**Comment by NQHuy1905** [comment]
@CHELSEA234 hi , i have sent sign of the DRA form via email ngqhuy1905@gmail.com can you share dataset with me
