### ISSUE TITLE
Typo with test script?

### ISSUE THREAD

**Issue by tangwudu** [CHELSEA234/Multi-domain-learning-FAS#15]
![20230815-184422](https://github.com/CHELSEA234/Multi-domain-learning-FAS/assets/3677630/8390f319-b54c-4dfd-b854-d658eb0e7c80)

Seems there is typo with the arrange of the model initialization.

**Comment by CHELSEA234** [comment]
i also notice this wrong naming, but weights are right and this does not impact the performance.
