### ISSUE TITLE
the requirements file is not clear

### ISSUE THREAD

**Issue by JavanehBahrami** [CHELSEA234/Multi-domain-learning-FAS#18]
Hi
Please add and a requirements file to define version of the required library for inferencing.
when I run the inference file I faced this error:
```python 
face-alignment is not defined
```

**Comment by CHELSEA234** [comment]
@JavanehBahrami  I think I have replied your email. let me know what else you need.

**Comment by JavanehBahrami** [comment]
Yes thanks a lot for your help
the package that I need to install was:
```
pip3 install face-alignment
```
