### ISSUE TITLE
Great work, but I would like to ask if the siw-m dataset is released ?

### ISSUE THREAD

**Issue by GSHZhang** [CHELSEA234/Multi-domain-learning-FAS#2]

**Comment by CHELSEA234** [comment]
yes. we will release it recently. plz give me your email and I can send you the link.

**Comment by cuiwenbing** [comment]
916150440@qq.com i need it   thanks

**Comment by GSHZhang** [comment]
gs.zhang0@gmail.com  thanks.

**Comment by MTQ819** [comment]
18352560851@163.com, thanks.

**Comment by LeeKyungwook** [comment]
dddrrreee@naver.com. Thanks

**Comment by clarkong** [comment]
clarkong89@gmail.com
Thanks

**Comment by sigpro** [comment]
x.wangyan@gmail.com Thanks

**Comment by CHELSEA234** [comment]
https://github.com/CHELSEA234/Multi-domain-learning-FAS/blob/main/source_SiWMv2/DRA_form_SIWMv2.pdf

Please fill out this form. @sigpro @clarkong  @LeeKyungwook @MTQ819
