### ISSUE TITLE
construct the MD-FAS benchmark

### ISSUE THREAD

**Issue by GSHZhang** [CHELSEA234/Multi-domain-learning-FAS#3]
When I construct the  FASMD dataset based on the list ([SIW E train](https://github.com/CHELSEA234/Multi-domain-learning-FAS/blob/main/dataset/SIW_list/E_train_sub_id_siw.txt) and [OULU E train](https://github.com/CHELSEA234/Multi-domain-learning-FAS/blob/main/dataset/OULU_list/E_train_oulu.txt)) you provided, I found that I got the E sub-dataset with 839(from siw)+1620(from oulu) videos, which is a lot more than the 1696 listed in the paper?

**Comment by CHELSEA234** [comment]
we have made changes on the benchmark in the paper, which contains governemnt data that is not allowed to share. We will update the arxiv.

**Comment by GSHZhang** [comment]
So, the benchmark provided [here](https://github.com/CHELSEA234/Multi-domain-learning-FAS/tree/main/dataset) is the final version?

**Comment by CHELSEA234** [comment]
> So, the benchmark provided [here](https://github.com/CHELSEA234/Multi-domain-learning-FAS/tree/main/dataset) is the final version?
@GSHZhang 
I am sorry for the last response. Yes, this is the final version.
In fact, many ids in three datasets  are repeated. This is because I want to make each spoof attack balanced. As you can imagine, the balance between different spoof attack helps the converge.
