### ISSUE TITLE
about data preprocessing

### ISSUE THREAD

**Issue by woody-panda** [CHELSEA234/Multi-domain-learning-FAS#4]
Thanks for sharing the code. I'm new to FAS and would be very grateful if you could give me some data preprocessing details.

1. According to the paper, the FAS model and framework are frame-based, right? In preprocessing, is it necessary to extract frames from the video? Then crop out the face from each frame? How many frames are extract from each video?

**Comment by CHELSEA234** [comment]
Thanks to your comments. :) 
Yes. Most FAS models are frame-based, except for a few works that takes videos (e.g., a few consecutive frames) as input. In my opinion, you have to extract frames given videos, and this is just one line of code using OpenCV; Cropping the face with bounding box, you can go with the off-the-shelf tools, such as _RetinaFace_ and _MTCNN_.

**Comment by tangwudu** [comment]
You will just use original cropped face or any padding based on face bounding box?
