### ISSUE TITLE
How to extract images from videos?

### ISSUE THREAD

**Issue by MMMMMz** [CHELSEA234/Multi-domain-learning-FAS#5]
Hi,

thank you very much for your work and for releasing the code :) I have read your code carefully but still have some doubts. How do you prepare datasets? And how can I get frames from videos? 

Looking forward to your reply....

**Comment by CHELSEA234** [comment]
Hi, I think you can use opencv to extract the video, for example: cap = cv2.VideoCapture(video_name)
