### ISSUE TITLE
About some questions

### ISSUE THREAD

**Issue by XinLi-0701** [CHELSEA234/Multi-domain-learning-FAS#7]
Thanks for sharing; this is a great job! 
However, this code seems to just have the SREnet part, doesn't have the FAS-wrapper part, maybe my understanding is wrong. If so, could you please share the code of FAS-wrapper? My email address is 815542315@qq.com. 
I really hope to get your reply. Thank you very much.

**Comment by CHELSEA234** [comment]
I need to extend FAS-wrapper for the journal submission, so this part is not available for the public now.
