### ISSUE TITLE
Request for pre-trained model on SiW-Mv2

### ISSUE THREAD

**Issue by raviy0807** [CHELSEA234/Multi-domain-learning-FAS#8]

**Comment by CHELSEA234** [comment]
hi, please take a look on https://drive.google.com/drive/folders/1CHIzOUyy3YvpDi-gP6nCIdOPHJWWxQQo

**Comment by raviy0807** [comment]
Hi,

Thanks for directing the link. I am trying to run the script for the inference : source/test_architecture.py

In this file, it requires trained model with 2 other folders of RE & G_Op as written here : https://github.com/CHELSEA234/Multi-domain-learning-FAS/blob/main/source/test_architecture.py#L68

Please guide me on this

Thanks

**Comment by raviy0807** [comment]
> hi, please take a look on https://drive.google.com/drive/folders/1CHIzOUyy3YvpDi-gP6nCIdOPHJWWxQQo

Hi @CHELSEA234 ,

Thanks for directing the link. I am trying to run the script for the inference : source/test_architecture.py

In this file, it requires trained model with 2 other folders of RE & G_Op as written here : https://github.com/CHELSEA234/Multi-domain-learning-FAS/blob/main/source/test_architecture.py#L68

Please guide me on this

Thanks
