### ISSUE TITLE
About the metrics

### ISSUE THREAD

**Issue by liangliangdeveloper** [CHELSEA234/Multi-domain-learning-FAS#9]
In the Paper, you use TPR@FPR=0.5% as metrics but this metric is not included in metric.py (But I find the TPR@FPR=0.2%, 5%, and 1%). And I am curious about the test_architecture.py because it can not work well for the function test_update not being used.

**Comment by CHELSEA234** [comment]
You can change the hyper-parameter in the metric.py to reflect the metric we have used in the paper.
I think test_architecture.py expects csv file as the output, and from this csv file you can compute all metrics as you wish. in this sense, 'test_update' is not being used.
